package co.csadev.kellocharts.formatter

import co.csadev.kellocharts.model.AxisValue
import co.csadev.kellocharts.model.BubbleValue
import co.csadev.kellocharts.model.PointValue
import co.csadev.kellocharts.model.SliceValue
import co.csadev.kellocharts.model.SubcolumnValue

interface AxisValueFormatter {
    fun formatValueForManualAxis(formattedValue: CharArray, axisValue: AxisValue): Int
    fun formatValueForAutoGeneratedAxis(
        formattedValue: CharArray,
        value: Float,
        autoDecimalDigits: Int
    ): Int
}

interface BubbleChartValueFormatter {
    fun formatChartValue(formattedValue: CharArray, value: BubbleValue): Int
}

interface ColumnChartValueFormatter {
    fun formatChartValue(formattedValue: CharArray, value: SubcolumnValue): Int
}

interface LineChartValueFormatter {
    fun formatChartValue(formattedValue: CharArray, value: PointValue): Int
}

interface PieChartValueFormatter {
    fun formatChartValue(formattedValue: CharArray, value: SliceValue): Int
}
